# Generated by Django 5.0.3 on 2024-03-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puntos_de_autoridad', models.PositiveIntegerField()),
                ('imagen', models.ImageField(upload_to='media/auras/')),
            ],
        ),
    ]
